# Default properties (applies to all profiles unless overridden)
spring:
    application:
        name: shopify-elasticsearch-poc
    elasticsearch:
        uris: http://localhost:9200  # Default Elasticsearch URI (can be overridden by profiles)

shopify:
    apiVersion: 2024-04

# Development environment specific settings
---
spring:
    profiles: dev
    elasticsearch:
        username: elastic
        password: gt3y00iKDtLX1K=xvCyV
    shopify:
        apiKey: 756a476055e05f5eb0747a3ca1191816
        apiSecret: e5ef854275aa39d72c9f0bfd8f6abb5c
        storeUrl: https://e7f461-0a.myshopify.com/
    sync:
        mode: all
        tenant:
            id: tenant_1 # Used if sync.mode=tenant

# Production environment specific settings
---
spring:
    profiles: prod
    elasticsearch:
        uris: http://localhost:9200
        username: elastic
        password: gt3y00iKDtLX1K=xvCyV
    shopify:
        apiKey: 756a476055e05f5eb0747a3ca1191816
        apiSecret: e5ef854275aa39d72c9f0bfd8f6abb5c
        storeUrl: https://e7f461-0a.myshopify.com/
    sync:
        mode: all
        tenant:
            id: tenant_1 # Used if sync.mode=tenant
